# Generated by Django 6.0.1 on 2026-02-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialization",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
