# Generated by Django 6.0.1 on 2026-02-05 12:54

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allergy",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="allergy",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="allergy",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="allergy",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_allergy_name_ci",
            ),
        ),
    ]
