[project]
name = "fit1056-hospital-management-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.1",
    "django-cors-headers>=4.9.0",
    "django-extensions>=4.1",
    "djangorestframework>=3.16.1",
    "djangorestframework-simplejwt>=5.5.1",
    "psycopg[binary]>=3.3.2",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.2.1",
    "uuid",
]

[dependency-groups]
format-and-lint = [
    "ruff>=0.14.14",
]
other = [
    "pre-commit>=4.5.1",
]
test = [
    "factory-boy>=3.3.3",
    "freezegun>=1.5.5",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-django>=4.11.1",
    "pytest-dotenv>=0.5.2",
    "pytest-env>=1.2.0",
    "pytest-mock>=3.15.1",
]

[tool.ruff]
target-version = "py313"
line-length = 88
extend-exclude = [
    "migrations"
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "B",
    "S",
    "T",
    "UP",
    #    "D", # Docstring rules, enable soon
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["S101", "S105", "S106"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"


[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "hospital_backend.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
#env_files = [".env.test"]
pythonpath = ["."]
addopts = [
  "--strict-config",
  "--strict-markers",
  "--tb=short"
]
markers = [
  "unit: fast isolated tests",
  "integration: tests with DB or external services",
  "e2e: full end-to-end tests",
]


[tool.coverage.run]
omit = [
    "tests/*",
    "*/migrations/*",
    "__init__.py",
]
